apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    release: {{ .Release.Name }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
